### ISSUE TITLE
手机版如何使用，编译后一直在加载中？

### ISSUE THREAD

**Issue by gxylfm** [FongMi/TV#10]
![image](https://user-images.githubusercontent.com/57065133/183241634-97bbd615-28d3-4610-81e3-7b0d6cf7ca65.png)

**Comment by FongMi** [comment]
還沒開始寫呢

gxylfm ***@***.***> 於 2022年8月6日 週六 16:38 寫道：

**Comment by FongMi** [comment]
待開發
