### ISSUE TITLE
同样的的直播m3u文件在别的APP一切正常，在影视APP就是黑屏。m3u文件部署在 gitcode

### ISSUE THREAD

**Issue by cnliucheng** [FongMi/TV#100]

**Comment by FongMi** [comment]
請檢查直播配置是否為影視的格式

**Comment by FongMi** [comment]
https://raw.githubusercontent.com/cnliucheng/iptv/main/my.m3u
這個嗎

**Comment by FongMi** [comment]
![image](https://github.com/FongMi/TV/assets/3471963/2cbb9da9-a884-42be-8c3f-db305f812077)

**Comment by cnliucheng** [comment]
https://gitcode.net/brokenway/iptv/-/raw/master/iptv.m3u




------------------ 原始邮件 ------------------
发件人: FongMi ***@***.***&gt;
发送时间: 2023年6月16日 11:18
收件人: FongMi/TV ***@***.***&gt;
抄送: Chris Liu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [FongMi/TV] 同样的的直播m3u文件在别的APP一切正常，在影视APP就是黑屏。m3u文件部署在 gitcode (Issue #100)





 
https://raw.githubusercontent.com/cnliucheng/iptv/main/my.m3u
 這個嗎

**Comment by FongMi** [comment]
因為 gitcode 封鎖 okhttp 的 ua。你沒收到消息嗎？
