### ISSUE TITLE
分类页面已经翻到最后一页，有可能出现重复请求情况

### ISSUE THREAD

**Issue by ghost** [FongMi/TV#101]
尊敬的作者，您好。
1. 使用的接口配置地址：https://ghproxy.com/raw.githubusercontent.com/gaotianliuyun/gao/master/0827.json
2. 选择的站源是：巴士，然后点播 --> 国产动漫 --> 分类选择 “动态漫画” 和 “2019”
3. 选择下面的影片后翻到最底部，再往上翻，再往下翻，重复这个操作，抓包请求，会发现这个筛选后的分类已经翻到最底部后，往回翻的过程会再次发起请求，如果此时再往底部翻页，又会继续发起请求。而页面明显已经没有数据了。
4. 操作过程我已经用视频记录了下来。视频地址：https://raw.githubusercontent.com/zhixc/file/main/video.zip
5. 对于这种情况，我尝试在自己的 spider 代码里面返回时增加过 pagecount、limit、total，但是 影视app 似乎并不是根据这些来判断是否有下一页，然后我又尝试用抛出异常的方式，结果也不能阻止 影视app 继续调用categoryContent() 方法，最后我想到了增加一个成员变量 hasNextPageMap 来判断和阻止。代码地址：https://github.com/zhixc/CatVodTVSpider/blob/main/app/src/main/java/com/github/catvod/spider/SP360.java
6. 请问有更好的方式来告诉 影视app 停止继续调用 categoryContent()方法吗？

最后，感谢您花时间看这个 issue。

**Comment by FongMi** [comment]
是的，在我看來這是正常的。

**Comment by ghost** [comment]
好的，我明白了，感谢您的回复。
