### ISSUE TITLE
安卓4.4手机使用TV 4.1 v2.0.0版的问题

### ISSUE THREAD

**Issue by rainy-lam** [FongMi/TV#103]
![Screenshot_2023-06-27-02-54-42](https://github.com/FongMi/TV/assets/12071755/fd34ded6-ef62-4ece-914e-547c94bd0f53)
大佬你好，最近在安卓4.4的手机上试用了您为安卓4.1电视开发的版本，发现两个问题，希望能解决，先谢谢了！
1.如图所示，APP不是全屏显示的，上方会一直显示一条黑色的状态栏，播放影片的时候也不会自动隐藏，很影响观感，希望可以将状态栏隐藏。
2.主页和点播向下滚动两行左右，会自动返回最上方，无法正常向下滚动。
以上两个问题在TV上应该是不存在的，我也知道这个版本是专为电视开发，并未针对手机做适配，只是手机版仅支持安卓5.0以上的设备。希望大佬能抽空修改一下，不胜感激！

**Comment by FongMi** [comment]
4.4 只有針對盒子適配，沒有心力在弄一個手機版，請見諒。
