### ISSUE TITLE
老大，文件夹可以重新支持1.7.5的大图标吗？

### ISSUE THREAD

**Issue by zengge99** [FongMi/TV#106]
我配合小雅使用。有个xiaoya-tvbox的项目给小雅文件夹做了海报图标。1.7.5版本文件夹可以显示成大图标，到1.8.0版本后变成列表式的小图标了，海报也就失去了意义。

**Comment by zengge99** [comment]
![IMG_20230630_221337](https://github.com/FongMi/TV/assets/83830807/6a44bb7e-15f1-460f-a70d-1bdbe41a8299)
1.7.5显示成这样的

**Comment by zengge99** [comment]
![IMG_20230630_224335](https://github.com/FongMi/TV/assets/83830807/89eb488b-f4d9-4d89-9577-eaa9a9177541)
2.0.0变这样了

**Comment by zengge99** [comment]
![IMG_20230630_064942_675](https://github.com/FongMi/TV/assets/83830807/b37a48fd-b9aa-4b57-80ca-f91f32ec0b90)
2.0.0变这样了

**Comment by FongMi** [comment]
待我調整 jar

**Comment by zengge99** [comment]
> 待我調整 jar

非常感谢！
