### ISSUE TITLE
安卓4.4TV，影视快进后转圈圈不消失

### ISSUE THREAD

**Issue by sosoyy123** [FongMi/TV#109]
安卓4.4TV，观看影视快进后，圈圈会一直在中心显示

**Comment by FongMi** [comment]
請提供測試地址及影片

**Comment by sosoyy123** [comment]
> 請提供測試地址及影片

项目主，换了多个共享地址，任何影片都一样

**Comment by klcb2010** [comment]
> 安卓4.4TV，观看影视快进后，圈圈会一直在中心显示

你安装的哪个版本分享一下？我用的2.0.5没法安装
