### ISSUE TITLE
[直播] 切换播放器黑屏

### ISSUE THREAD

**Issue by alchemist2018** [FongMi/TV#110]
你好。
以下情况在leanback-4.1上出现。
自己写了个包涵2套直播源的json，第一套"playerType": 0，第二套"playerType": 2.
从第二套切换到第一套，屏幕黑屏无声。
此时点一次返回键返回到fongmi主界面，再点直播，第一套可以正常播放。

这是bug吗？能否修复？

**Comment by FongMi** [comment]
給我測試源
