### ISSUE TITLE
[直播] rtp://225.1.1.120:5002这类的组播地址，直播电视台列表不显示，也就无法播放了

### ISSUE THREAD

**Issue by gongbaojiding1** [FongMi/TV#111]
rtp://225.1.1.120:5002这类的组播地址，直播电视台列表不显示，也就无法播放了，请问是bug吗？能否修复？

**Comment by FongMi** [comment]
應該是你配置問題，可以丟配置給我檢查看看。

**Comment by gongbaojiding1** [comment]
CCTV1,http://ktwlplkf.f3322.org:9901/tsfile/live/0001_1.m3u8
CCTV2,rtp://225.1.1.120:5002

这个直播地址列表，在FongMi直播模块中只显示CCTV1,CCTV2不显示

**Comment by FongMi** [comment]
我是說配置，不是源

**Comment by gongbaojiding1** [comment]
我说的不显示是直播模块左边电视台列表中不显示CCTV2,跟配置无关！是apk读取直播源文件时忽略了rtp开头的源

**Comment by FongMi** [comment]
我測試是有的哦

**Comment by FongMi** [comment]
所以才要看你配置是怎寫的

**Comment by FongMi** [comment]
我猜你是貓影視舊版寫法吧，jar只會讀 http 的地址，請用影視的寫法
![image](https://github.com/FongMi/TV/assets/3471963/02a0c975-67d7-4fbb-9081-aa2b85b035b1)

**Comment by FongMi** [comment]
https://github.com/FongMi/TV/blob/release/other/sample/live/online.json

**Comment by gongbaojiding1** [comment]
刚才测试下，rtp开头的直播源可以显示和播放，发现两个问题：
1是配置直播源时只能读取txt格式的直播源文件，m3u格式的不行
2直播模块解码设置没有系统解码，点播有系统解码

**Comment by FongMi** [comment]
1. m3u 我測試也沒問題
2. 有的，你再仔細看看吧

**Comment by gongbaojiding1** [comment]
直播配置：file://localhost/电视.txt txt格式的可以读取并播放
file://localhost/电视.m3u, m3u格式的直播模块电视台列表显示是空的，没有读取出电视台列表

**Comment by gongbaojiding1** [comment]
直播模块解码只有ijk和exo,我的盒子是安卓6，ijk解码正常，exo不能播放

**Comment by FongMi** [comment]
建議你上tg問吧，如果真不行早就炸鍋了。
