### ISSUE TITLE
Android 4.4.4系统，Konka Android TV 638，surfaceview模式下视频宽不能铺满屏幕宽，TextureView可以

### ISSUE THREAD

**Issue by linhua55** [FongMi/TV#112]
Android 4.4.4系统，Konka Android TV 638，surfaceview模式下视频宽不能铺满屏幕宽，TextureView可以。
但是TextureView性能不如surfaceView，而且TextureView偏向冷色调，surfaceView模式下视频偏向暖色调。
![IMG_20230716_133109](https://github.com/FongMi/TV/assets/6326116/a92489d6-5d52-481d-babe-65c897e46643)

目前只在这个电视上出现这个问题。这里只是记录一下问题，准备这几个星期调试改下。由于这个电视不能开启adb。所以准备使用远程logcat日志。  https://andych008.github.io/posts/571c1dd7/

**Comment by FongMi** [comment]
系統問題，無解，控件都是 exo 原生無改的

**Comment by linhua55** [comment]
用的ijk，exo太卡了。但是surfaceview下16:9，填充及裁剪，都是可以充满屏幕的。但是这个充满不是按视频比例，导致视频纵向拉伸了。视频 3840*1610，视频充满屏幕（纵向上下没有黑边，应该是有黑边的）
