### ISSUE TITLE
中英双语字幕能否改进为并列显示

### ISSUE THREAD

**Issue by mavnp** [FongMi/TV#113]
bug：
![Screenshot_20230721_202731_com.fongmi.android.tv.jpg](https://github.com/FongMi/TV/assets/92003405/2e210d12-1fd6-463d-a303-1ea283b65b64)

感谢大佬持续更新该应用，该应用的自动换源是我目前用的最舒服的，希望能改进一下这个问题

**Comment by FongMi** [comment]
提供字幕連結我看看

**Comment by mavnp** [comment]
> 提供字幕連結我看看

https://www.aliyundrive.com/s/HGyd1kWK7Us
这是我图片里的电影文件，由于字幕是内封的而我没了解过这方面，所以没办法直接提供字幕文件，抱歉
昨天我在easybox（不知道您听说过吗）里用同样的源看过该影视，字幕是分行显示的，所以提了这个issue

源是https://tvbox.cainisi.cf，视频是里面的玩偶云盘源1第一个

**Comment by FongMi** [comment]
EXO挺正常的

**Comment by FongMi** [comment]
IJK下個版本修

**Comment by mavnp** [comment]
> IJK下個版本修

收到，感谢大佬，我先用exo好了
