### ISSUE TITLE
进一步提高用户体验的需求

### ISSUE THREAD

**Issue by youtvbox** [FongMi/TV#114]
1.搜索对源的过滤，调用搜索的时候只使用对应的勾选的spider，可以过滤掉已经失效的源或者地区效果不好的源。可以参考美化版的方式

2.在“自动无法使用的时候”遇到源“错误的时候中断自动切换

3.自动切换可以追加”喜好源“：在自动切换的时候可以有线切换该源

4.spider中阿里云盘技术栈，在手机版使用的时候，可以追加一个button、类似：”请求手机授权“，这样手机用户不用通过云盘扫码、类似alipay的授权

**Comment by FongMi** [comment]
1. 已經有了
2. 很正常
3. 我的jar有了
