### ISSUE TITLE
magnet play function

### ISSUE THREAD

**Issue by BOX168** [FongMi/TV#118]
Hi,please add magnet play function,thank you !

**Comment by FongMi** [comment]
請提交PR，謝謝。

**Comment by BOX168** [comment]
hi,Fongmi大神：
&nbsp; &nbsp; &nbsp; 抱歉，菜鸟没找到怎么提交。上次邮件中提到2个库文件，libxl_stat.so&nbsp; &nbsp;, libxl_thunder_sdk.so,&nbsp; 是否还需要libp2p.so这个库文件。
&nbsp; &nbsp; 再次感谢您百忙之中回复邮件。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FongMi/TV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FongMi/TV] magnet play function (Issue #118)





 
請提交PR，謝謝。
