### ISSUE TITLE
Some of magnet media cann't be play,and Show "...limit“

### ISSUE THREAD

**Issue by BOX168** [FongMi/TV#125]
Hello,20230803#2 and other versions , when playing some magnetic media, display  “... Limit”, automatically jump other source .
But install other version of tvbox, and then return to play this magnet media  be OK  with fongmi tvbox .
Thanks！

**Comment by FongMi** [comment]
給我測試地址

**Comment by BOX168** [comment]
Hi, can try link  that  magnet:?xt=urn:btih:00366cd764aecfa66202033b02b878105a0b287a&dn=[www.mp4us.com]别叫我赌神.2023.HD10800p.国粤双语中字.mp4. And Q215613905 tvbox.
Best regards.

**Comment by FongMi** [comment]
![image](https://github.com/FongMi/TV/assets/3471963/233b483f-7d2b-45c6-992e-1f39be5a16da)

**Comment by BOX168** [comment]
![Screenshot_2023-08-03-23-11-53-833_com fongmi android tv](https://github.com/FongMi/TV/assets/139636782/f407b8fd-69fd-4c08-9679-b1a7302236e5)
先清空应用数据，从配置https://ghproxy.com/raw.githubusercontent.com/gaotianliuyun/gao/master/XYQ.json，搜索：我不是“赌神”,Mp4电影里第1个链接进去。

**Comment by BOX168** [comment]
Before
![Screenshot_2023-08-03-23-11-53-833_com fongmi android tv](https://github.com/FongMi/TV/assets/139636782/053d58ec-7877-4dac-aa06-b9bc99e7e310)

Strange, but  reboot tvbox  can play now.

**Comment by BOX168** [comment]
Thanks a lot.
