### ISSUE TITLE
建议不直接显示历史记录

### ISSUE THREAD

**Issue by klcb2010** [FongMi/TV#126]
历史记录占用了屏幕位置，使得推荐的影片不方便查看。能否把它放到按钮中，需要的时候再点击出现？效果类似于图片以下。
![Screenshot_2023-08-06-12-14-38-610_com github tvbox keshimax](https://github.com/FongMi/TV/assets/32628414/a95ab89b-a09d-4023-a765-277738f89522)

**Comment by FongMi** [comment]
不考慮，影視為貓影視復刻版。
