### ISSUE TITLE
可以复现的BUG

### ISSUE THREAD

**Issue by GXG12345** [FongMi/TV#127]
辛苦了，手机版(py-64位)在播放界面点开更多的情况(保持)下，切换手机暗色模式或者夜间模式会导致软件崩溃，猜测是不是BaseDialog.java里没写完

**Comment by GXG12345** [comment]
错误信息
Stack trace:
java.lang.NullPointerException:
Attempt to invoke interface
method java.util.lterator
java.util.List.iterator()' on a null
object reference
at
com.fongmi.android.tv.ui.custo
m.dialog.EpisodeGridDialog.set
SpanCount(EpisodeGridDialog
java:69)
comfongmi.android.tv.ui.custo
m.dialog.EpisodeGridDialog.init
View(EpisodeGridDialog.java:6
2
com.fongmi.android.tv.ui.custo
m.dialog.BaseDialog.onViewCr
eated(BaseDialogjava:32)
at
androidx.fragment.app.Fragme
nt.performViewCreated(Fragm
entjava:2987)
at
androidx.fragment.app.Fragme
ntStateManagercreateView(Fr
agmentStateManagerjava:546
at
androidx.fragment.app.Fragme
ntStateManagermoveToExpect
edState(FragmentStateManag
erjava:282)
at
androidx.fragment.app.Fragme
ntStore.moveToExpectedState(
FragmentStorejava:112)
androidx.fragment.app.Fragme
ntManager.moveToState(Frag
mentManagerjava:1647)
at
androidx.fragment.app.Fragme
ntManager.dispatchStateChan
ge(FragmentManagerjava:312
at
androidx.fragment.app.Fragme
ntManager.dispatchActivityCre
ated(FragmentManagerjava:3
072)
at
androidx.fragment.app.Fragme
ntControllerdispatchActivityCr
eated(FragmentControllerjava:
251)
androidx.fragment.app.Fragme
ntActivity.onStart(FragmentAc
tivityjava:502)
at
androidx.appcompat.app.App
CompatActivity.onStart(AppCo
mpatActivityjava:251)
at
com.fongmi.android.tv.ui.activit
y.DetailActivity.onStart(DetailA
ctivityjava:1379)
at
android.app.lnstrumentation.c
allActivityOnStart(Instrumenta
tionjava:1469)
at
android.app.Activity.performSt
art(Activityjava:8155)
at
android.app.ActivityThread.ha
ndleStartActivity(ActivityThrea
djava:3840)
TransactionExecutor.performLi
fecycleSequence(TransactionE
xecutorjava:221
android.app.servertransaction.
TransactionExecutor.cycleToPa
th(TransactionExecutorjava:20
android.app.servertransaction
TransactionExecutorexecuteLi
fecycleState(TransactionExecu
torjava:173)
at
android.app.servertransaction.
TransactionExecutor.execute(T
ransactionExecutorjava:97)
at
android.app.ActivityThread$H
handleMessage(ActivityThrea
djava:2374)
at
android.os.Handler.dispatchMe
ssage(Handlerjava:106)
at
android.os.LooperloopOnce(Lo
operjava:233)
at
android.os.Looperloop(Looperj
ava:344)
at
android.app.ActivityThread.ma
in(ActivityThreadjava:8249)
at
java.lang.reflect.Method.invok
e(Native Method)
at
com.android.internal.os.Runtim
elnit$MethodAndArgsCaller.ru
n(Runtimelnit;java:589)
at
comandroid.internal.os.Zygote
lnit.main(Zygotelnit;java:1071)

**Comment by FongMi** [comment]
是，這是我隱藏的 bug，暫時無解。
