### ISSUE TITLE
手机版下载功能

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [FongMi/TV#129]
改了好久才发现大佬这个库,感谢在前

如手机版的下载/缓存在计划中,可否添加调用IDM下载功能
通勤路上信号不好,比较依赖离线视频
功能:
![image](https://github.com/FongMi/TV/assets/62411322/256d0ca8-8f56-406c-849e-e2eae086c39c)
代码:
`    private void use1DMDownload() {
        if (vodInfo != null && vodInfo.seriesMap.get(vodInfo.playFlag).size() > 0){
            VodInfo.VodSeries vod = vodInfo.seriesMap.get(vodInfo.playFlag).get(vodInfo.playIndex);

            // 创建Intent对象，启动1DM App
            Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(vod.url));
            intent.setDataAndType(Uri.parse(vod.url), "video/mp4");
            intent.putExtra("title", vodInfo.name+" "+vod.name); // 传入文件保存名
            //intent.setClassName("idm.internet.download.manager.plus", "idm.internet.download.manager.MainActivity");
            intent.setClassName("idm.internet.download.manager.plus", "idm.internet.download.manager.Downloader");
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

            // 检查1DM App是否已安装
            PackageManager pm = getPackageManager();
            List<ResolveInfo> activities = pm.queryIntentActivities(intent, 0);
            boolean isIntentSafe = activities.size() > 0;

            if (isIntentSafe) {
                startActivity(intent); // 启动1DM App
            } else {
                // 如果1DM App未安装，提示用户安装1DM App
//                AlertDialog.Builder builder = new AlertDialog.Builder(this);
//                builder.setTitle("请先安装1DM+下载管理器");
//                builder.setMessage("为了下载视频，请先安装1DM+下载管理器。是否现在安装？");
//                builder.setPositiveButton("立即下载", new DialogInterface.OnClickListener() {
//
//                    public void onClick(DialogInterface dialog, int which) {
//                        // 跳转到下载链接
//                        Intent downloadIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://od.lk/d/MzRfMTg0NTcxMDdf/1DM _v15.6.apk"));
//                        startActivity(downloadIntent);
//                    }
//                });
//                builder.setNegativeButton("取消", null);
//                builder.show();
            }
        } else {
            ToastUtils.showShort("资源异常,请稍后重试");
        }
    }`

**Comment by FongMi** [comment]
善用分享按鈕
