### ISSUE TITLE
部分配置地址无法解析

### ISSUE THREAD

**Issue by ZZMHA227** [FongMi/TV#13]
https://raw.liucn.cc/m.json
https://cdn.jsdelivr.net/gh/Cyril0563/lanjing_live@main/TVbox_Free/tv.txt
这两个配置地址，前段时间可以解。但最近又无法解析了，不知道问题在哪。其他由tvbox改的可以正常使用。
大佬麻烦看看，顺颂时祺。

**Comment by FongMi** [comment]
https://raw.liucn.cc/m.json
293 格式錯誤，"filterable":1"}  多個 "，應該是  "filterable":1}

https://cdn.jsdelivr.net/gh/Cyril0563/lanjing_live@main/TVbox_Free/tv.txt
測試正常，請檢查網路連線
