### ISSUE TITLE
9978端口推送得配置页面

### ISSUE THREAD

**Issue by dream7180** [FongMi/TV#130]
设置页推送到手机，只能用搜索页面，底下得推送和配置按钮没有作用，望解决，感谢！

**Comment by FongMi** [comment]
測試沒問題，謝謝。

**Comment by dream7180** [comment]
> 測試沒問題，謝謝。

奇怪了，我TV盒子上装的是python_arm32版的，手机上firefox和xbrowser上均是如此，设置不了

**Comment by dream7180** [comment]
pc上也不行，不是浏览器问题，我录制的视频您看看。

https://github.com/FongMi/TV/assets/18242221/211a6547-12c5-4b50-ae12-d290cae9894f
