### ISSUE TITLE
还是9987端口网页配置页问题，有视频您看看。

### ISSUE THREAD

**Issue by dream7180** [FongMi/TV#131]
安装的是32位的 python 版（TV），配置页在pc和手机浏览器都都不行，不是浏览器问题，我录制的视频您看看。

https://github.com/FongMi/TV/assets/18242221/211a6547-12c5-4b50-ae12-d290cae9894f

_Originally posted by @dream7180 in https://github.com/FongMi/TV/issues/130#issuecomment-1694595814_

**Comment by FongMi** [comment]
https://github.com/FongMi/TV/assets/3471963/0a279e85-b1dd-47dd-9324-ab4478014edf

這是我的測試結果，建議您清一下瀏覽器快取或是紀錄
