### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by rvnox** [FongMi/TV#132]
手机版建议允许隐藏下方的直播

**Comment by FongMi** [comment]
不採納，建議刪除直播配置即可

**Comment by rvnox** [comment]
> 不采纳，建议删除直播配置即可
删除配置后，再次重新打开软件后还是会默认加载和点播一样的配置，下面还是会有直播，能否不要默认加载呀

**Comment by FongMi** [comment]
你可以自己弄個配置

**Comment by rvnox** [comment]
好吧，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月30日(星期三) 晚上11:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FongMi/TV] 小建议 (Issue #132)





 
你可以自己弄個配置
