### ISSUE TITLE
此类源播放不了

### ISSUE THREAD

**Issue by dgshilong** [FongMi/TV#135]
https://prd-vcache.edge-global.akamai.tvb.com/v5/newsbks/_definst_/smil:news/inews1/20230906/archive_26_752814_1280_720_1500k_cht_proenv_can.smil/playlist.m3u8?hdnea=ip=0.0.0.0~st=1694068426~exp=1694154826~acl=/v5/newsbks/_definst_/smil:news/inews1/20230906/archive_26_752814_1280_720_1500k_cht_proenv_can.smil/*~hmac=3fdb46813e7776f763eb008f3b7ceaaab83a992d9b42491f4a8fad99bd679129

老大，此类源播放不了，IJK EXO 都解不了。

**Comment by FongMi** [comment]
已回報給 google
