### ISSUE TITLE
.js 和 drpy file

### ISSUE THREAD

**Issue by kentanttw** [FongMi/TV#136]
你好， 请问怎么用这两种files 在 影视app?

![image](https://github.com/FongMi/TV/assets/65578562/a526dd85-4837-4d26-a3d6-5513effa329e)

**Comment by FongMi** [comment]
請至群組發問，會有很多好心人回覆您。

**Comment by kentanttw** [comment]
哪一个群？

**Comment by FongMi** [comment]
https://t.me/fongmi_offical/

**Comment by kentanttw** [comment]
我被禁发言
