### ISSUE TITLE
添加PyramidStore本地PY爬虫的问题。

### ISSUE THREAD

**Issue by lm317379829** [FongMi/TV#14]
PyramidStore本地PY爬虫，可以支持使用Python来写爬虫逻辑，需要将pyramid.aar集成入apk，项目地址如下：
https://github.com/UndCover/PyramidStore
小白在编译过程中遇到两个问题：
***1. 编译提示找不到/exo/core_settings.gradle文件，将https://github.com/google/ExoPlayer项目clone下后编译报错。***
> Task :app:checkMobileReleaseDuplicateClasses
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/bean/Collect.java:15: error: cannot find symbol

        return new Collect(Site.get("all", ResUtil.getString(R.string.collect_all)), new ArrayList<>());
                                                                     ^
  symbol:   variable collect_all
  location: class string
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/mobile/java/com/fongmi/android/tv/ui/fragment/SettingFragment.java:66: error: cannot find symbol
        AppDatabase.clear();
                   ^
  symbol:   method clear()
  location: class AppDatabase
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/mobile/java/com/fongmi/android/tv/ui/fragment/HomeFragment.java:72: error: cannot find symbol
        mHistoryAdapter.addAll(AppDatabase.get().getHistoryDao().getAll());
                                                                ^
  symbol:   method getAll()
  location: class HistoryDao
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
***2.向ApiConfig.java文件中添加如下内容后***
public Object[] proxyLocal(Map param) {
    //pyramid-add-start
    try {
        if(param.containsKey("api")){
            String doStr = param.get("do").toString();
            if(doStr.equals("ck"))
                return PythonLoader.getInstance().proxyLocal("","",param);
           Site site = getSite(doStr);
            return PythonLoader.getInstance().proxyLocal(site.getKey(), site.getExt(), param);
        }else{
            String doStr = param.get("do").toString();
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal("","",param);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    //pyramid-add-end
    return jarLoader.proxyInvoke(param);
}
**编译报错：**
> Task :exoplayer-extension-ima:extractReleaseAnnotations
WARNING: [Processor] Library '/home/runner/.gradle/caches/modules-2/files-2.1/com.google.ads.interactivemedia.v3/interactivemedia/3.26.0/2583e7eb3c63bcee42b830dc3776dc96b8a86a7f/interactivemedia-3.26.0.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/Nullable'
 Example of support library reference: 'android/support/annotation/Nullable'
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:124: error: method setConfig in class PythonLoader cannot be applied to given types;

        PythonLoader.getInstance().setConfig(Prefers.getUrl(),object.toString());
                                  ^
  required: String
  found: String,String
> Task :app:compileLeanbackReleaseJavaWithJavac FAILED
  reason: actual and formal argument lists differ in length
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:192: error: incompatible types: Map<CAP#1,CAP#2> cannot be converted to Map<String,String>
                return PythonLoader.getInstance().proxyLocal("","",param);
                                                                   ^
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:194: error: incompatible types: Map<CAP#1,CAP#2> cannot be converted to Map<String,String>
            return PythonLoader.getInstance().proxyLocal(site.getKey(), site.getExt(), param);
                                                                                       ^
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:197: error: incompatible types: Map<CAP#1,CAP#2> cannot be converted to Map<String,String>
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal("","",param);
                                                                                        ^
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
4 errors

**Comment by FongMi** [comment]
請用 dev 分支解決 exo 編譯問題
