### ISSUE TITLE
关于日志输出问题！

### ISSUE THREAD

**Issue by yjczxccom** [FongMi/TV#141]
有计划添加WebSocket以支持drpy的日志输出吗？

**Comment by FongMi** [comment]
沒有吧，搞得太複雜，用貓影視的debug工具吧。

**Comment by yjczxccom** [comment]
貓影視的debug没有WebSocket方便，有个大佬魔改的直接在http:x.x.x.x:9978/log就可以很直观的显示了，但是他的版本没有你的好用！

**Comment by yjczxccom** [comment]
貓影視的debug没有WebSocket方便好用，有个大佬魔改的直接在http:x.x.x.x:9978/log就可以很直观的显示了，但是他的版本没有你的好用！
