### ISSUE TITLE
线路屏蔽功能失效了？

### ISSUE THREAD

**Issue by klcb2010** [FongMi/TV#144]
电视端已经没有屏蔽功能了，试了一下手机端 即使屏蔽了也没作用  照样能收到被屏蔽的线路资源
![Screenshot_2023-09-30-18-39-31-671_com fongmi android tv](https://github.com/FongMi/TV/assets/32628414/ce4c8075-d030-4df7-9dda-a84a079dde28)
![Screenshot_2023-09-30-18-44-01-793_com fongmi android tv](https://github.com/FongMi/TV/assets/32628414/af70f716-29de-42a8-ae25-bb2e77e891a2)

**Comment by FongMi** [comment]
那是換源功能.....

**Comment by klcb2010** [comment]
> 那是換源功能.....
屏蔽线路的功能在TV版  消失了

**Comment by FongMi** [comment]
沒消失....
