### ISSUE TITLE
猫影视编译的js加载

### ISSUE THREAD

**Issue by FoxNick** [FongMi/TV#145]
byte[] a = new byte[1];
                    a[0] = 1;
                    byte[] b = Base64.decode(str3.replace("//bb",""), 0);
                    InputStream bais = new ByteArrayInputStream(b, 5, b.length); // 创建字节数组输入流
                    //bais.skip(5);

                    byte[] ab = byteMerger(a, toByteArray(bais));
找到猫影视字节码改动处理的方法 现在主要是他那种导出函数如何处理

**Comment by FoxNick** [comment]
有qq啥的联系方式吗 可以加个交流一下

**Comment by FongMi** [comment]
這個我試過囉，一樣不行。

**Comment by FoxNick** [comment]
可以已经搞通了

**Comment by FoxNick** [comment]
有qq吗

**Comment by FoxNick** [comment]
字节码那样处理 另外要在调用字节码接口处增加 设置模块名

**Comment by FoxNick** [comment]
if(str3.startsWith("//bb")){
                    byte[] b = Base64.decode(str3.replace("//bb",""), 0);
                    quickJS.execute(byteFF(b),  key +  ".js");
                    quickJS.evaluateModule("import {__jsEvalReturn} from '" + key + ".js';\n\nglobalThis." + key + " = __jsEvalReturn();\n\n"
                            + "console.log(typeof(pdfl));console.log(Object.keys(globalThis." + key + "));");

                    //LOG.e("222", "B>" + Arrays.toString(quickJS.getKeys(getContext().getGlobalObject())));
                }

**Comment by FoxNick** [comment]
https://gitee.com/foxnick/drpyboxd
引擎用这个项目的aar
部分测试代码在这里QuJsEngine.java

你测试看看可以运行部分编译好的 阿里的两个有报错 没看那两个js源码

**Comment by FoxNick** [comment]
这个引擎是自己修改编译的 用的优化版quickjs性能比原版快40+ jni大部分使用你现在用的那个 我修改并加了些东西

**Comment by FoxNick** [comment]
他的引擎编译开启了CONFIG_BIGNUM所以前面是2猫影视没开启前面是1

**Comment by FoxNick** [comment]
关闭CONFIG_BIGNUM编译 前面改成1 就ok了

**Comment by FoxNick** [comment]
为了能准确获取到模块名 所以在执行字节码接口上增加 自定义名字 就可以用导入模块方式 把js的接口赋值到全局 用一套代码 兼容

**Comment by FongMi** [comment]
好的，感謝愛佬，我請另一個大佬跟您聯繫，他對quickjs 也比較熟悉。
