### ISSUE TITLE
增加字幕调整大小

### ISSUE THREAD

**Issue by ihuaer** [FongMi/TV#150]
部分在线高清视频采用的是软字幕，目前是可以选择字幕，但是默认字幕很小，能否增加调整字幕大小的功能

**Comment by FongMi** [comment]
已經有了

**Comment by liujixu1984** [comment]
请教在哪里调整字幕大小呀

**Comment by FongMi** [comment]
共通：設定中長按播放器
手機：播放中長按字幕
電視：焦點在字幕上下調整

**Comment by liujixu1984** [comment]
非常感谢 另外可以调位置吗 有的字幕在黑边中间十分难受
