### ISSUE TITLE
大佬，能加个播放长按左右滑动改变倍数播放功能么

### ISSUE THREAD

**Issue by AlanTse1314** [FongMi/TV#152]
类似这样的，播放时长按快进播放，长按时左右拖动切换倍数
![E27D1112-05E8-4AE8-8EE7-6A48B74C72E8](https://github.com/FongMi/TV/assets/88262891/56fd2e84-914f-4fa7-ac75-ef9e7daea47a)

**Comment by FongMi** [comment]
不考慮
