### ISSUE TITLE
mitv播放断流

### ISSUE THREAD

**Issue by Piscen** [FongMi/TV#159]
mitv://的链接播放个10分钟左右就断了,然后一直加载中，手动选一下台又正常播放了，必现问题。
这是链接还是播放器的问题呢。
测试链接：mitv://generationnexxxt.com:19806/4f6345e5f86944b5b495fc33310a43f3

**Comment by FongMi** [comment]
斷流難免，正常情況會接續上，不然你買正版看囉。

**Comment by Piscen** [comment]
我是想探讨一下问题出在哪以及有没有办法解决，不正面回答问题却让我去买正版，然后直接给我关了issue，我真怀疑你这2K+是不是刷来的

**Comment by FongMi** [comment]
問題在於正版有心跳帳密驗證，我們這是偷的，所以斷流很正常。
2k+也是刷來的，靠大家推廣，所以是刷的。
