### ISSUE TITLE
老哥考不考虑将直播独立成一个APP

### ISSUE THREAD

**Issue by wshizhx** [FongMi/TV#161]
手机上好的直播都不太好，有时候只想看一下直播

**Comment by InitialXKO** [comment]
或者加个选项，启动直接进入直播，方便老人使用

**Comment by FongMi** [comment]
不可以

**Comment by FongMi** [comment]
@InitialXKO 20231126 已支持

**Comment by sunzongzheng** [comment]
> @InitialXKO 20231126 已支持

@FongMi 请问这个入口在哪里，在`2.1.2`版本的设置里没看到
