### ISSUE TITLE
请问时移功能是取消了吗？ 哪个版本还有保留

### ISSUE THREAD

**Issue by biner** [FongMi/TV#164]
app/src/main/java/com/fongmi/android/tv/model/LiveViewModel.java

checkPLTV是被注释掉的
//checkPLTV(item);

<img width="869" alt="微信图片_20231126162924" src="https://github.com/FongMi/TV/assets/860760/32e3896d-7ca6-4d32-86fc-31c2d8d5a35e">

**Comment by FongMi** [comment]
還沒開始寫
