### ISSUE TITLE
去广告

### ISSUE THREAD

**Issue by ynyhuh** [FongMi/TV#165]
http://饭太硬.top/tv
“一起|App”
电影
鹦鹉杀
或其它都一样。
广告位置10:00
没专业学习过，百度即学修改
IjkUtil.java
m3u8Ad改为true
if (true) uri = Uri.parse(Server.get().getAddress().concat("/m3u8?url=").concat(URLEncoder.encode(uri.toString())));

M3U8.java
//             if (response.header(HttpHeaders.ACCEPT_RANGES) != null) return "";

Nano.java
String result = M3U8.get(url, session.getHeaders()).replaceAll("#EXT-X-DISCONTINUITY[\\s\\S\\n]*?#EXT-X-CUE-IN", "");

Ijk播放，广告去除！方法相信是有问题。
可能有遗漏，访问github困难，发现或对话也补充不了问题，应该可以明白。

**Comment by FongMi** [comment]
廣告需要規則處理，你沒看過海外看的切片，請增長見聞。
