### ISSUE TITLE
NewPipeExtractor的依赖现在是找不到了吗？

### ISSUE THREAD

**Issue by skyshenfu** [FongMi/TV#167]
同步代码后gradle好像解决不了这个依赖

**Comment by FongMi** [comment]
我測試沒問題，版本也跟官方一致。
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/build.gradle

**Comment by fza3230200** [comment]
确实依赖不了

**Comment by FongMi** [comment]
依賴不了就拿掉吧，再把錯誤部分移除就好，這是Youtube解析而已。
