### ISSUE TITLE
如何设置直播默认使用exo播放器？

### ISSUE THREAD

**Issue by wzl0904** [FongMi/TV#169]
直播默认都是IJK播放器，家里的TCL电视播放联通IPTV组播转发的直播源会卡顿，使用exo播放器没问题，但是设置里修改默认播放器对直播不起作用呢，有没有方法设置直播的默认播放器？？

**Comment by FongMi** [comment]
配置設定
playerType = 2

**Comment by FongMi** [comment]
請參考
https://github.com/FongMi/TV/blob/release/other/sample/live/online.json

**Comment by wzl0904** [comment]
> 請參考 https://github.com/FongMi/TV/blob/release/other/sample/live/online.json

方法有效 感谢
