### ISSUE TITLE
安卓4.x版

### ISSUE THREAD

**Issue by JeremyXING** [FongMi/TV#175]
非常感谢蜂蜜大佬的工作，dev版更新了直播自启的功能非常好用简直是老年人的福音～但由于家里老人的电视只能装上4.x版的目前，想问下啥时候会发正式版呢或者能发个4.x版本的测试版吗？等了几个礼拜实在是没等到所以问问。。。。。。

影视天下第一！

**Comment by FongMi** [comment]
快了，估計下個禮拜。
