### ISSUE TITLE
电视用着出现程序错误

### ISSUE THREAD

**Issue by zyzyzy523** [FongMi/TV#184]
日志是内存分配不够，OOM了
![img_v3_0267_a6ade103-b52b-4dcd-9ba0-367dcb171cag](https://github.com/FongMi/TV/assets/48322364/9b75d1e2-4688-417a-8f5a-a4b7c2cc73bf)
![img_v3_0267_3a5dcde0-3585-42ee-84c3-4f1c4ccc9c0g](https://github.com/FongMi/TV/assets/48322364/3ec764fd-4387-48ff-9af6-d496ae44b7f5)

**Comment by FongMi** [comment]
請隨時關注 tg 群，因為 gh-proxy 代理惡意塞100mb檔案，更新至 2.1.2 就會正常了。
