### ISSUE TITLE
可否增加一个数据上传接口

### ISSUE THREAD

**Issue by shawn996** [FongMi/TV#191]
使用了很多站源（几千），但不知道哪些已经坏掉了，一条条的检查又很费功夫。
可不可以添加一条自定义的URL接口，使用影视观看的时候，可以把播放数据提交到指定url上（比如站点key、播放的url，视频状态），这样就可以在观看的时候，分析出哪些接口挂掉了，那些是好用的。方便维护sites、lives列表。

ps：还有历史播放同步接口，这样就可以多台设备同步啦。

**Comment by FongMi** [comment]
可以自己寫java排查的，加油。
