### ISSUE TITLE
关于油管节目播放问题

### ISSUE THREAD

**Issue by q10878** [FongMi/TV#196]
安卓7虚拟机可以正常直播和推送，安卓4，安卓5电视机环境只能播放和推送24小时直播类节目，
比如https://www.youtube.com/watch?v=oIgbl7t0S_w
其他的节目均解析失败

**Comment by q10878** [comment]
补充下，即便是路由器全局代理情况，也必须在设置页面设置好代理，然后在配置文件里加上
{ "name": "proxy", "hosts": [ ""googleapis.com"] },才可以正常播放油管节目

**Comment by FongMi** [comment]
如果你有設置 proxy，不管你路由器有沒有全局，一律走proxy，然後 proxy 需要配置中設定域名。
