### ISSUE TITLE
软件有严重bug

### ISSUE THREAD

**Issue by lzk23559** [FongMi/TV#20]
如题，使用xb，xp的规则时，如果某个分类的内容不够一页显示时会触发自动加载下一页，造成无限触发网络请求，变成DDOS。

**Comment by lzk23559** [comment]
@FongMi 

https://raw.githubusercontent.com/422678320/320/d0230bd9b926386a2a4f710ff44804b3697b27e9/TVBox/0888.json

🥒大米星球(XB)  励志片分类

**Comment by FongMi** [comment]
測試沒有問題，只會問到第2頁，就不會再自動觸發。

**Comment by lzk23559** [comment]
@FongMi 我是安装在手机上测试规则触发的。电视上没法抓包，也不知道具体情况。

**Comment by FongMi** [comment]
在手機上使用發生的bug，一律不處理哦。
