### ISSUE TITLE
FongMi/tv端还有手机端，在哪添加token啊

### ISSUE THREAD

**Issue by beyonder588** [FongMi/TV#200]
TV端和手机端阿里的一直跳过换源，出现了一个什么海阔添加token的提示，飞快闪过，那到底怎么添加token啊，就这一点太不方便了

**Comment by ghost** [comment]
如果你用的接口是 https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/config.json，那么把里面的 影視天下第一 这6个字换成真实有效的token，举个例子：假设你真实的token为 7abcdefgxxxxxxxx7abcdefgxxxxxxxx
配置文件里面的
{"key": "盤99", "name": "盤99", "type": 3, "api": "csp_Pan99", "searchable": 1, "changeable": 0, "ext":"影視天下第一" },
改成
{"key": "盤99", "name": "盤99", "type": 3, "api": "csp_Pan99", "searchable": 1, "changeable": 0, "ext":"7abcdefgxxxxxxxx7abcdefgxxxxxxxx" },

**Comment by FongMi** [comment]
token 由爬蟲包管理，不是殼子處理。
