### ISSUE TITLE
[Bug report] exoplayer 缩放异常

### ISSUE THREAD

**Issue by samefow** [FongMi/TV#201]
使用exoplayer播放器设置 16:9 或者 4:3 缩放时，实际上并不能按照设置进行缩放，请作者检查一下，谢谢。

**Comment by FongMi** [comment]
這功能很久了，通常是電視盒子設置問題，尤其是刷過機的。

**Comment by samefow** [comment]
直接用release源代码编译的话就会出现上面的问题，比较生成的mobile-java-arm64_v8a.apk文件，会发现跟 https://github.com/FongMi/Release/blob/main/apk/release/mobile-java-arm64_v8a.apk 相比，在`lib/arm64-v8a`中少了`libffmpegJNI.so`和`libgav1JNI.so`两个文件，如果用dev分支的源代码编译的话，会提示`Could not read script 'C:\Project\TV\media\core_settings.gradle' as it does not exist.`而无法编译，原因是在`.gitignore`中存在`/media*`导致media*文件夹没有同步到github。

**Comment by FongMi** [comment]
是的，exo 本身不支持這些比例縮放，需自行下載源碼修改。

**Comment by samefow** [comment]
能否提供一下您修改的代码？谢谢。
