### ISSUE TITLE
配置取得失败

### ISSUE THREAD

**Issue by focus2846** [FongMi/TV#202]
2.1.5版本配置的时候就失败，是不是Android14的原因？

**Comment by FongMi** [comment]
請提供測試案例

**Comment by focus2846** [comment]
手机型号是IQOO NEO9 ，android 14 ，
我另一部手机可以正常配置的，三星NOTE 20U ，android 13

![微信图片_20240102083513](https://github.com/FongMi/TV/assets/6268423/3d8742c7-7899-4a36-ae61-2940ee27b945)

**Comment by FongMi** [comment]
請檢查儲存權限，已詢問過群裡安卓14用戶，本地配置沒問題。
