### ISSUE TITLE
[Bug report] IJKPlayer无法播放rtsp视频流

### ISSUE THREAD

**Issue by samefow** [FongMi/TV#203]
用exoplayer可以播放，但ijk播放不了，测试源可以在 https://rtsp.stream 获取。

**Comment by FongMi** [comment]
可以直接提供測試地址。

**Comment by samefow** [comment]
rtsp://rtspstream:4b1dd4a9ada45e5d312dd4829fd761e4@zephyr.rtsp.stream/pattern

不确定有效期多长。

**Comment by FongMi** [comment]
確實不支持，但無法修正，因為 ijk 不是我的主力。
但並不是所有 rstp 不支持，只是剛好這個不支持。

**Comment by FongMi** [comment]
好像又能放
![image](https://github.com/FongMi/TV/assets/3471963/c4b179fe-1021-493c-8f20-d910a25d1001)

**Comment by samefow** [comment]
确实可以了，那就先这样吧。

**Comment by samefow** [comment]
不过好像ijk不是很稳定，有时候行有时候不行，exo测试每次都可以。

**Comment by FongMi** [comment]
ijk 就垃圾阿，B站又沒繼續維護，新代碼也不放。

**Comment by samefow** [comment]
有没有可能把ijk换成vlc？有些rtsp视频源用vlc可以播放，exo播放不了。

**Comment by samefow** [comment]
vlc支持的视频格式和协议多，还有持续更新的[libvlc](https://mvnrepository.com/artifact/org.videolan.android/libvlc-all)。

**Comment by FongMi** [comment]
沒有吧，主力依舊是exo。
