### ISSUE TITLE
嗅探的live直播存在ts流失效的问题

### ISSUE THREAD

**Issue by hick1213** [FongMi/TV#216]
目前webview版本中嗅探获取的url,在播放一段时间会出现complete的情况,需要获取新的url才能继续.但是如果不停的切换的话,目前的播放器好像会出现卡顿,需要有proxy直接不停的去buffer

**Comment by FongMi** [comment]
來源問題，通常是php沒寫好，建議你搞個 jar 代理處理，播放器邏輯都是 exo 原生處理。

**Comment by TYHeke** [comment]
有sample可以提供一下么
