### ISSUE TITLE
大佬 这个1080资源站不显示影片所有列表下面都是空的，Q版可以正常显示 可以看一下吗是哪里的问题吗

### ISSUE THREAD

**Issue by xuanjinok** [FongMi/TV#22]
{
      "key": "1080",
      "name": "1080（采）",
      "type": 1,
      "api": "https://api.1080zyku.com/inc/apijson.php?ac=list",
      "searchable": 1,
      "quickSearch": 1,
      "filterable": 1,
      "categories": [
        "国产剧",
        "香港剧",
        "台湾剧",
        "泰国剧",
        "海外剧",
        "日本剧",
        "韩国剧",
        "欧美剧",
        "综艺",
        "纪录片",
        "动画片",
        "武侠片",
        "动作片",
        "喜剧片",
        "爱情片",
        "科幻片",
        "恐怖片",
        "剧情片",
        "战争片",
        "动漫"
      ]
    },

**Comment by FongMi** [comment]
已修正，請重新下載倉庫APK。
