### ISSUE TITLE
Android Tv

### ISSUE THREAD

**Issue by WhyredHuang** [FongMi/TV#23]
Download
[TV-Java](https://github.com/FongMi/TV/blob/main/release/leanback-java.apk?raw=true)
[TV-Python](https://github.com/FongMi/TV/blob/main/release/leanback-python.apk?raw=true)

I am using Android TV,  Which file i am download ?

**Comment by FongMi** [comment]
If you have py api, download python version.

**Comment by WhyredHuang** [comment]
i am using hisense 32 inch android smart tv

where can i check this tv using Py Api ?


Thanks bro

**Comment by FongMi** [comment]
If u are using the url for config
https://raw.githubusercontent.com/UndCover/PyramidStore/main/py.json

u will need py version.

**Comment by WhyredHuang** [comment]
I am using this Config :
https://github.com/YuanHsing/freed/blob/master/TVBox/meow.json
https://github.com/YuanHsing/freed/blob/master/TVBox/MaooXB2/1080Kkk.json

**Comment by FongMi** [comment]
Just use java version

**Comment by WhyredHuang** [comment]
Thanks Bro
