### ISSUE TITLE
大佬 我的山东移动直播源有很多播放不了 源测试过了都没失效 是解码的问题吗？

### ISSUE THREAD

**Issue by xuanjinok** [FongMi/TV#24]
CCTV13,http://39.137.76.32:8089/00/SNM/CHANNEL00000345/index.m3u8
CCTV4,http://39.137.76.32:8089/00/SNM/CHANNEL00000320/index.m3u8
CCTV7,http://39.137.76.32:8089/00/SNM/CHANNEL00000318/index.m3u8
CCTV8,http://39.137.76.32:8089/00/SNM/CHANNEL00000362/index.m3u8
CCTV6,http://39.137.76.32:8089/00/SNM/CHANNEL00000361/index.m3u8
CCTV1,http://39.137.76.32:8089/00/SNM/CHANNEL00000311/index.m3u8
CCTV10,http://39.137.76.32:8089/00/SNM/CHANNEL00000321/index.m3u8
CCTV9,http://39.137.76.32:8089/00/SNM/CHANNEL00000319/index.m3u8
山东卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000301/index.m3u8
山东齐鲁,http://39.137.76.32:8089/00/SNM/CHANNEL00000313/index.m3u8
济南都市,http://39.137.76.32:8089/00/SNM/CHANNEL00000062/index.m3u8
山东综艺,http://39.137.76.32:8089/00/SNM/CHANNEL00000338/index.m3u8
天津卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000327/index.m3u8
北京卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000302/index.m3u8
湖南卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000324/index.m3u8
浙江卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000305/index.m3u8
东方卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000309/index.m3u8
江苏卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000304/index.m3u8
安徽卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000328/index.m3u8
东南卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000310/index.m3u8
黑龙江卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000306/index.m3u8
辽宁卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000326/index.m3u8
吉林卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000363/index.m3u8
江西卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000335/index.m3u8
河南卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000358/index.m3u8
贵州卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000329/index.m3u8
重庆卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000341/index.m3u8
广东卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000307/index.m3u8
广西卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000368/index.m3u8
四川卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000348/index.m3u8
河北卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000330/index.m3u8
海南卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000347/index.m3u8
湖北卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000325/index.m3u8
陕西卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000029/index.m3u8
青海卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000366/index.m3u8
甘肃卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000349/index.m3u8
宁夏卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000043/index.m3u8
山西卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000032/index.m3u8
深圳卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000308/index.m3u8
云南卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000367/index.m3u8
内蒙古卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000040/index.m3u8
西藏卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000045/index.m3u8
新疆卫视,http://39.137.76.32:8089/00/SNM/CHANNEL00000044/index.m3u8
CCTV4欧洲,http://39.137.76.32:8089/00/SNM/CHANNEL00000350/index.m3u8
CCTV4美洲,http://39.137.76.32:8089/00/SNM/CHANNEL00000351/index.m3u8
CCTV2,http://39.137.76.32:8089/00/SNM/CHANNEL00000317/index.m3u8
CCTV11,http://39.137.76.32:8089/00/SNM/CHANNEL00000344/index.m3u8
CCTV12,http://39.137.76.32:8089/00/SNM/CHANNEL00000322/index.m3u8
CCTV17,http://39.137.76.32:8089/00/SNM/CHANNEL00000303/index.m3u8

**Comment by FongMi** [comment]
等我加上 ijk 吧
