### ISSUE TITLE
几个功能操作建议

### ISSUE THREAD

**Issue by jefcn** [FongMi/TV#25]
1.主界面可否将最近观看收起来，放到“历史”按钮里（出于隐私考虑）
2主界面可否像tvbox一样把点播站的各分类直接展示出来（现在必须要点点播进去，多了一道操作路径，而且有时因为没有成功加载导致点不动用户会产生疑惑）
3.播放界面菜单键弹出窗口可否改为类似diyp的右侧抽屉式菜单？这样遥控器选择操作更方便
4.直播界面对于可时移的源，可否直接按左右键后退前进？现在是必须点菜单键，弹出播放条，然后移动到播放进度条，最后才能后退前进，操作过于繁琐，且逻辑与点播播放不一致
5.搜索结果过于模糊，无法精确搜索

**Comment by FongMi** [comment]
此軟件為致敬貓影視，所以介面只會借鑒貓影視哦。
其他細節請在群組討論。

**Comment by jefcn** [comment]
> 此軟件為致敬貓影視，所以介面只會借鑒貓影視哦。 其他細節請在群組討論。

fongmi就是fongmi，不必拘泥于一定要跟猫影视一摸一样，不好的体验没必要继承

**Comment by klcb2010** [comment]
> > 此軟件為致敬貓影視，所以介面只會借鑒貓影視哦。 其他細節請在群組討論。
> 
> fongmi就是fongmi，不必拘泥于一定要跟猫影视一摸一样，不好的体验没必要继承

想提这个问题  很久了  没想到作者拒绝
