### ISSUE TITLE
对自动换源的建议

### ISSUE THREAD

**Issue by kkv0id** [FongMi/TV#315]
问题：在网络不稳定或最理想源不稳定时会自动切源（大概率到一个赌博广告很多的源中），想切会原来的源几乎需要重新搜索，最下方的源列表无之前源（被屏蔽了？），历史记录也没，只有切之后源的记录。
建议：只在当前源不同线路之间切换，自动切换源提供开关，或者弹窗让用户选择其它源并提供切源的取消按钮。
使用作者的fongmi有近一个月了，方方面面都挺满意，在线下线上也安利给不少人了，由衷希望越来越好。

**Comment by FongMi** [comment]
自动切换源已有开关。

**Comment by kkv0id** [comment]
@FongMi 我用的安卓版，刚刚看了下没有换源开关，没看到安卓的库，所以提交在TV仓库下了

**Comment by FongMi** [comment]
請上TG發問比較快哦。
