### ISSUE TITLE
哪位大神能解决阿里token的添加后依然无法播放阿里云盘内容的问题

### ISSUE THREAD

**Issue by beyonder588** [FongMi/TV#318]
目前leanback端使用 ‘’高天留云‘’线路，以及‘’PG‘’两条线路，里边都自带网盘配置菜单，可是两个线路都是设置好阿里云盘的token后依旧无法播放阿里盘内容的情况，夸克盘正常，哪位大神能帮忙解惑，谢谢了。

另：大佬能否考虑开发下将token脱离出jar包，可以通过扫码或者输入自动添加到线路里，目前很多线路都不自动弹出阿里扫码的提示框，而且大部分线路即使扫码了，也依旧无法观看阿里，尤其leanback端最甚。

mobile端莫名其妙的有时候就可以播放，不稳定

**Comment by FongMi** [comment]
人的問題...
