### ISSUE TITLE
leanback-java是目前用过的解码最好的版本，不过py_ali.py解析有问题，有目录无内容。

### ISSUE THREAD

**Issue by tvbw** [FongMi/TV#34]
测试过其他tvbox版本，py_ali.py搜索播放没有问题，同理盘搜、云搜py都一样有问题，可以搜索出目录，打开目录都是空，其它几个版本不存在这个问题，建议测试改正。

**Comment by FongMi** [comment]
py阿里系列被我閹割了，因為我寫的jar就有了。
