### ISSUE TITLE
about p2p protocols

### ISSUE THREAD

**Issue by vipeweb** [FongMi/TV#36]
Hello, first great job I would like to understand a little more about the integrated p2p protocols, such as forcetv, tvbus

first i thought forcetech forcetv was dead, is it still possible to create streamer forcetv?

I'm looking for a way to create my own p2p stream to use with these libs, do you have any documentation or something to share? I searched but found nothing

**Comment by FongMi** [comment]
Sorry, I don't have tool to create p2p stream.
BinStream have product for tvbus.
You can contact them.

**Comment by vipeweb** [comment]
thanks, binstream seems to have abandoned tvbus.

referring to forcetech do you know if it still works?

**Comment by FongMi** [comment]
I think forcetech is dead too.

**Comment by FongMi** [comment]
Now zlive and mitv is works well.
But I only have url to play, don't have server.

**Comment by vipeweb** [comment]
zlive and mitv seems new to me

do you know their official website address?

**Comment by FongMi** [comment]
Sorry, I don't have.
Just know some app is use zlive and mitv.
普視 and 晴天
