### ISSUE TITLE
1.5.7没有看到轨道功能了

### ISSUE THREAD

**Issue by jefcn** [FongMi/TV#39]

**Comment by FongMi** [comment]
為了兼容 ijk 軌道，切成音軌跟字幕，有1個以上軌道才會顯示按鈕，沒有顯示就是預設或是無。

**Comment by jefcn** [comment]
> 

这样就看不到当前视频的分辨率信息了

**Comment by jefcn** [comment]
> 為了兼容 ijk 軌道，切成音軌跟字幕，有1個以上軌道才會顯示按鈕，沒有顯示就是預設或是無。
这样就看不到当前视频的分辨率信息了

**Comment by jefcn** [comment]
> 為了兼容 ijk 軌道，切成音軌跟字幕，有1個以上軌道才會顯示按鈕，沒有顯示就是預設或是無。

这样就看不到当前视频的分辨率信息了

**Comment by jefcn** [comment]
> 為了兼容 ijk 軌道，切成音軌跟字幕，有1個以上軌道才會顯示按鈕，沒有顯示就是預設或是無。

请问新版在哪里查看当前视频的分辨率信息呢

**Comment by FongMi** [comment]
暫停可以看到

**Comment by FongMi** [comment]
直播看不到

**Comment by jefcn** [comment]
> 直播看不到

可以考虑一下增加遥控器菜单键（右键）功能哦。
这样在直播时：菜单键→各功能选项，上下键→换台，左右键→换源或时移（优先时移）
点播时：菜单键→各功能选项，上下键→上下集（如有），左右键→时移（或保留现有操作习惯也可以）
