### ISSUE TITLE
软件自动换源播放时，刷新出现索引越界异常

### ISSUE THREAD

**Issue by ghost** [FongMi/TV#42]
尊敬的作者，您好，我在使用您的软件时，接口是饭太硬提供的接口：http://饭太硬.ga/x/o.json，发现了一个bug。
    我搜索厕所英雄后，选择播放源“野荷塘 | SP”，然后进入播放界面，接着等待了一会，软件切换其他播放源，最后播放失败，这时候，进入全屏视频，然后点击“刷新”，就出现问题。
    产生bug的具体操作过程我用视频记录下来了，视频地址：https://raw.githubusercontent.com/zhixc/tv-file/main/Screenrecorder-2023-02-13-21-22-47-688.zip
    解压后即可查看具体bug产生过程。
    希望您有空可以看下，然后修复bug，在此非常感谢您开发的这个软件，我非常喜欢这个软件，特别是自动换源机制，这一点非常不错。最后再次说声谢谢您。

**Comment by FongMi** [comment]
感謝回報，下個版本修正。

**Comment by FongMi** [comment]
1.6.5 已修正
