### ISSUE TITLE
使用老刘的接口，播放视频时出现空指针异常

### ISSUE THREAD

**Issue by ghost** [FongMi/TV#53]
&nbsp;&nbsp;尊敬的作者，您好。

&nbsp;&nbsp;我今天在使用老刘的接口进行测试时，选择视频源“音范丝”，然后选择一个视频进行播放的时候发现软件产生空指针异常。具体操作过程我录制了视频，地址：https://raw.githubusercontent.com/zhixc/tv-file/main/video.zip

老刘的接口：https://raw.liucn.cc/box/m.json

&nbsp;&nbsp;希望您有空的时候能够看一下，在此感谢您了。

**Comment by FongMi** [comment]
不支援 magnet 哦，所以造成閃退。

**Comment by ghost** [comment]
了解了，感谢回复。
