### ISSUE TITLE
能增加XWalkView吗？

### ISSUE THREAD

**Issue by mzlipro** [FongMi/TV#64]
有些安卓4设备需要XWalkView才能嗅探播放，有可能增加吗？

**Comment by FongMi** [comment]
已前加過，但大多盒子閃退，所以放棄，不會再考慮。

**Comment by mzlipro** [comment]
> 已前加過，但大多盒子閃退，所以放棄，不會再考慮。

新的手机测试版，选集部分影视会被影响
![Uploading P30425-011048.jpg…]()

**Comment by mzlipro** [comment]
![P30425-011048](https://user-images.githubusercontent.com/80456523/234069360-c04dca99-7cf0-49ad-8510-5d7400afa9b7.jpg)
