### ISSUE TITLE
感谢这么好的共享软件，有两个建议供参考完善，谢谢。

### ISSUE THREAD

**Issue by tvbw** [FongMi/TV#68]
1、EXO解码大部分阿里原盘无法播放（包括部分电视节目源），只有声音没有图像，改用IJK播放卡顿。改用pythonbox系统解码播放测试没有问题，EXO可以降码播放。如果exo无法解决建议增加原系统解码功能。
2、部分外置字幕自动读取后播放是乱码，用pythonbox测试正常。不知道什么原因。
3、无法在线手动搜索字幕，建议完善增加在线手动搜索字幕，如能更改在线字幕大小、颜色、调整字幕时间就更完美了。
以上仅供参考，感谢作者的辛勤劳动！

**Comment by FongMi** [comment]
1. 我的exo是最新的，無法播放要檢討自己設備哦，不想用ijk的系統解碼，因為沒什麼用處。
2. 因為字幕編碼格式不是UTF-8
3. 這個功能應該不會加，因為有些字幕屬於特效字幕，exo會還原最真實的特效。
