### ISSUE TITLE
能否在App 打包时加入  org.codelibs:jcifs:2.1.34 并排除 jcifs 包名的混淆

### ISSUE THREAD

**Issue by junwuwei** [FongMi/TV#70]
一直有用 SMB  播放 nas 中的 视频文件需求，但华为电视机 自带的 文件管理 访问smb 经常卡。

 几种基于tvbox 播放smb 的方式
 1  修改 ffmpeg ijk 源码 加入 smb 协议， 非常麻烦需要重新编译ffmpeg ijk smb。。。。 放弃
 
 2 在 tvbox 里面  ijk 实现 IMediaDataSource 播放可播放smb，   exo 实现 HttpDataSource 可播放smb  ，更新太频繁 每次合并 麻烦
 
 
 3  在catvodspider 里面实现 用http代理smb 流。  容易，不需要每次更新。

q版 和 taka 版 一直都正常，但现在已经切到fongmi tv版了，发现 app壳没有自带 jcifs 
每次更新 都需要自己重新打包把  jcifs 包引用进去 比较麻烦，作者更新太勤奋了。

jcifs 还依赖 org.bouncycastle:bcprov-jdk18on:1.71   注意排除混淆

**Comment by FongMi** [comment]
你可以至爬蟲那邊提交 SMB 的 PR
