### ISSUE TITLE
[mobile]投屏错误故障和两个建议

### ISSUE THREAD

**Issue by rubidzhu** [FongMi/TV#72]
1、使用mobile 1.1.1版本投屏电视机时出现下面的错误提示，无法投屏。
![image](https://user-images.githubusercontent.com/108105222/235174259-fd0ac9f7-1b49-4c9b-b425-5bfd3dfe09a1.png)
2、两个建议 ：
a) 播放界面是否可以增加速度的选项窗口，方便选择速度？
b)快速搜索结果是否新增活动窗口显示，更方便查看搜索结果。
3、请问下直播和投屏功能为什么没合入release分支？
谢谢！

**Comment by FongMi** [comment]
1. 不知道，要去詢問作者，可以去看我用哪個 lib
2. 不會，這不是 tvbox。
3. 之後才會放
