### ISSUE TITLE
蜂蜜 大佬  alist 目录获取不到内容

### ISSUE THREAD

**Issue by smjcxf1** [FongMi/TV#74]
蜂蜜 大佬  alist 目录有密码的话二级目录获取不到内容  一级有时也不好用
1.7.2和之前的都没有问题可以访问 之后就不行了  麻烦大佬修修

**Comment by FongMi** [comment]
這跟殼沒關係哦，alist只是個爬蟲。

**Comment by smjcxf1** [comment]
> 這跟殼沒關係哦，alist只是個爬蟲。

大佬 那我用你之前的版本可以用 1.7.2的可以 没有出现问题

**Comment by FongMi** [comment]
你可以抓包看一下差異
