### ISSUE TITLE
设置页的播放器设置IJK和电影播放页点播放器进行设置所用的播放器EXO不同步

### ISSUE THREAD

**Issue by 000tv** [FongMi/TV#76]
没法上传图片，不知道大神能看得懂没？

设置页的播放器设置IJK和电影播放页点播放器进行设置所用的播放器EXO不同步
意思就是设置页选了IJK，但是到播放电影那里的播放器用的还是EXO

**Comment by dgshilong** [comment]
您好，开发者，
