### ISSUE TITLE
[mobile]找不到CastDialog文件

### ISSUE THREAD

**Issue by rubidzhu** [FongMi/TV#79]
hi 大佬：
    投屏功能有使用到CastDialog，但是在您的release/dev分支均没有找到此文件，请问下此文件的位置在哪里？
detailactivity：
import com.fongmi.android.tv.ui.custom.dialog.CastDialog;
   谢谢！

**Comment by FongMi** [comment]
請用 release 分支，dev分支暫時沒開源哦。
