### ISSUE TITLE
可否将视频帧率直接显示在播放界面

### ISSUE THREAD

**Issue by qinef** [FongMi/TV#81]
非常感觉作者的作品，简直追剧神器，但是现在视频码率显示没有tvbox那么直观，要点到视频那个选项才会显示具体的帧率，望实现。

**Comment by FongMi** [comment]
點一下就會顯示。

**Comment by qinef** [comment]
就是点一下才能显示，不够直观，不像tvbox，点进播放界面就会在左上角显示1080*720这种字样，对于想找高清源的人来说稍显麻烦了点。
