### ISSUE TITLE
影片在两个网站无法播放时会循环换源，希望作者能够再次改进一下

### ISSUE THREAD

**Issue by ghost** [FongMi/TV#83]
尊敬的作者，您好。
我使用的接口是：https://raw.kgithub.com/zhixc/TVBox_config/main/v.json

在打开豆瓣站源选择电影，筛选华语、80年代，往下翻找到《江湖情》，选择这部电影后，接下来软件会自动换源，先是换到酷云77，然后是奇艺，接下来这两个网站都无法播放，一直循环切换，这里如果解析接口刚好都无法播放时，我想软件就会一直循环切换下去，又一次出现了死循环。操作记录我用视频录制了下来，压缩包地址是：https://raw.githubusercontent.com/zhixc/TVBox_config/main/video.7z

软件的自动换源机制，作者大大有空的时候能否改进一下，在此感谢您了。

**Comment by FongMi** [comment]
今日內測版再試試看，預計下午五點前更新。

**Comment by ghost** [comment]
好的，感谢🙏

**Comment by ghost** [comment]
刚测试了最新的开发版，没有出现上面这个问题了，谢谢您改进了这个软件。^_^
