### ISSUE TITLE
远程升级链接在哪里啊？

### ISSUE THREAD

**Issue by gwcctv** [FongMi/TV#84]
找了半天没找到？我看版本号处点击有升级检测

**Comment by rubidzhu** [comment]
连接到此仓库的版本目录地址。

**Comment by FongMi** [comment]
https://github.com/FongMi/TV/blob/release/app/src/mobile/java/com/fongmi/android/tv/Updater.java

**Comment by mlcs-top** [comment]
BuildConfig. 源码眉有这个文件
