### ISSUE TITLE
[Bug] 手机版本（mobile-Python）更新1.1.5后无法解析js源配置

### ISSUE THREAD

**Issue by lumingzh** [FongMi/TV#86]
如题，未测试TV版本，手机版本更新至1.1.5后无法解析JS源配置，导致视频源大量失效，首页豆瓣推荐无法显示，历史记录无法播放（但有缓冲网速显示），仅直播可正常使用。

1.1.4一切正常。

**Comment by lumingzh** [comment]
重新安装1.1.4版本后问题依旧，可能不是软件的bug，关闭issue了。

**Comment by klcb2010** [comment]
能分享一下手机版吗？我目前的症状和你一样
