### ISSUE TITLE
p2p-p8p,mitv

### ISSUE THREAD

**Issue by AlanTse1314** [FongMi/TV#88]
怎么播放p2p://和mitv://地址的直播源呀

**Comment by FongMi** [comment]
放進去 txt 配置

**Comment by AlanTse1314** [comment]
mitv://generationnexxxt.com:19806/9fd9601feb7545e5941996eaefd3fcc3
播放不了呀

**Comment by AlanTse1314** [comment]
CCTV1,p2p://generationnexxxt.com:19806/fefa49169743472ba6c1757f91ed00e1
CCTV2,p2p://generationnexxxt.com:19806/b2bba5ad68384401a465683b3f02ae03
CCTV3,p2p://generationnexxxt.com:19806/3f9746250d4d4a10a2c8e45e2d8c23da
CCTV4,p2p://generationnexxxt.com:19806/d2a14b2b50104d21ae1e25fa12115617
这几个地址都播不了🥲

**Comment by FongMi** [comment]
p2p改成 mitv ，播不了通常是地址過期了

**Comment by AlanTse1314** [comment]
好吧，那p3p,p4p,p5p...p9p都是一样的吗
