### ISSUE TITLE
直播m3u格式，解析无链接的频道

### ISSUE THREAD

**Issue by lucawong** [FongMi/TV#89]
"lives": [
    {
      "name": "M3U",
      "url": "http://abc.com/list.m3u"
    }

直播里，M3U格式，会解析没有m3u8视频链接.。也就是在频道列表里能看到这个没有m3u8的电影台1，但是不能播放。可以改变这个设置吗？让没有视频地址的被忽略。谢谢
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://abc.com/logo/dyt1.png" group-title="000",电影台1
#h/ttp://epg.112114.xyz/aaaaa.m3u8

**Comment by FongMi** [comment]
請自行修正連結。
