### ISSUE TITLE
手机版1.1.8播放酷云七七的JOJO英语启蒙字母歌 第四集 正常 升级1.2.0后提示不支持的格式

### ISSUE THREAD

**Issue by cyao2q** [FongMi/TV#98]
手机版1.1.8播放酷云七七的JOJO英语启蒙字母歌 第四集 正常 升级后提示不支持的格式

![image](https://github.com/FongMi/TV/assets/10820724/b1a3ec11-6f2b-4f1e-9ee7-1464091c747c)

**Comment by FongMi** [comment]
有調整解析邏輯
調整為解析到的地址不去確認播放地址是否可連結
所以解到的站源可能無法播放。
