### ISSUE TITLE
创维电视安卓4.4系统配置失败

### ISSUE THREAD

**Issue by agoai25** [FongMi/TV#99]
大佬，我的创维老电视昨天(2023-06-15)安装的tvbox,下载地址是:https://ghproxy.com/https://raw.githubusercontent.com/FongMi/TV/kitkat/release/leanback.apk
设置完点播地址(https://too.st/4Vk)后就崩溃了。请帮忙看下，万分感谢！报错如下:

Build version: 1.8.2
Current date: 2023-06-15 23:06:43
Device: Skyworth Inc. Skyworth 8H83 M6
OS version: Android 4.4.2 CI (SDK 19)

Stack trace:
java.lang.NoSuchMethodError:
com.google.gson.JsonParser.parseString
  at m5.d.w(SourceFile)
  at m5.c.run(SourceFile)
  at java.lang. Thread.run (Thread java:841)

如图
![20230616-084251](https://github.com/FongMi/TV/assets/136766991/d824b41f-4e16-4648-9aed-809c6d8b177a)

**Comment by FongMi** [comment]
無解，重新安裝看看吧。

**Comment by agoai25** [comment]
出现这个报错后，我当时就重装了，还是不行...
大佬，是电视系统版本太低的原因吗?

**Comment by FongMi** [comment]
清除資料重裝呢
